services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'transaction_teste'
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=dev
            - RABBITMQ_DEFAULT_PASS=devteste

    

  